import Testing
@testable import BST

/// Milestone 2 — mutant detectability, validated differentially against the
/// reference. The under-mutant verdicts below were generated by applying each
/// mutant to the reference Python impl (with correct recursion) and evaluating
/// all 52 witnesses. Our Swift mutant bodies must reproduce them exactly.
@Suite("Mutants")
struct MutantTests {

    /// All witnesses are counterexamples (`false`) under their mutant EXCEPT
    /// `insert_3/InsertUnion`: that input only inserts a *fresh* key, so it
    /// never triggers insert_3's equal-key value bug — it stays `true`, on both
    /// clean and mutant (confirmed against the reference). So this is the lone
    /// non-counterexample in `etna.toml`'s recorded witnesses.
    private static let nonCounterexamples: Set<String> = ["insert_3/InsertUnion"]

    @Test("Swift under-mutant verdicts match the reference on every witness")
    func underMutantMatchesReference() throws {
        for row in etnaWitnesses {
            guard let mutant = Mutant(rawValue: row.mutation) else {
                Issue.record("no Mutant case for \(row.mutation)")
                continue
            }
            let args = try witnessArgs(row.input)
            let result = try evaluate(property: row.property, args: args, mutant: mutant)
            let expected = MutantTests.nonCounterexamples.contains("\(row.mutation)/\(row.property)")
            #expect(
                result == expected,
                "\(row.mutation)/\(row.property) on \(row.input): expected \(expected) under mutant, got \(String(describing: result))"
            )
        }
    }

    /// Detectability: a mutant is *caught* when some witness passes on clean but
    /// fails under the mutant. Every mutant except the equivalent `union_8`
    /// must be caught by at least one witness.
    @Test("every non-equivalent mutant is caught by a witness")
    func everyRealMutantIsCaught() throws {
        var caught: Set<String> = []
        for row in etnaWitnesses where row.expected {
            guard let mutant = Mutant(rawValue: row.mutation) else { continue }
            let args = try witnessArgs(row.input)
            let clean = try evaluate(property: row.property, args: args)
            let mutated = try evaluate(property: row.property, args: args, mutant: mutant)
            if clean == true && mutated == false { caught.insert(row.mutation) }
        }
        let expected = Set(Mutant.allCases.map(\.rawValue)).subtracting(["none", "union_8"])
        #expect(caught == expected, "caught \(caught.sorted()), expected \(expected.sorted())")
    }

    /// `union_8` is byte-for-byte the clean body in the reference — an
    /// equivalent mutant, so it must be behaviourally indistinguishable.
    @Test("union_8 is an equivalent mutant (indistinguishable from clean)")
    func union8IsEquivalent() {
        let t1: Tree = .T(.T(.E, 0, 0, .E), 2, 5, .T(.E, 4, 1, .E))
        let t2: Tree = .T(.E, 1, 7, .T(.E, 3, 9, .E))
        #expect(union(t1, t2) == withMutant(.union_8) { union(t1, t2) })
    }
}
