import Testing
@testable import BST

/// Every `(mutation, property, witness)` row from ETNA's `etna.toml` ground
/// truth, paired with the verdict the *reference* (etna-python-bst) clean
/// implementation produces for it (`expected`).
///
/// Note: these witnesses are NOT all pass-on-clean. 16 of 52 evaluate `false`
/// on the clean reference too — many properties precondition `isBST` on only
/// *some* arguments, so a witness carrying an invalid-BST argument fails on the
/// correct impl as well as the mutant. The `expected` column was generated by
/// running the reference Python spec on each input, so this test is a
/// differential faithful-port proof: our Swift verdict must match the reference
/// verdict on every ground-truth input.
private let witnesses: [(mutation: String, property: String, input: String, expected: Bool)] = [
    // insert_1
    ("insert_1", "InsertPost", "((T E 2 1 E) 0 2 0)", true),
    ("insert_1", "InsertModel", "((T E 1 0 E) 0 0)", true),
    ("insert_1", "DeleteInsert", "((T E 1 0 E) 0 0 0)", true),
    ("insert_1", "InsertInsert", "(E 1 0 0 0)", false),
    ("insert_1", "InsertUnion", "(E (T E 1 1 E) 0 0)", false),
    ("insert_1", "UnionDeleteInsert", "((T E 2 0 E) E 0 0)", false),
    // insert_2
    ("insert_2", "InsertPost", "((T E 0 1 E) 1 0 0)", true),
    ("insert_2", "InsertModel", "((T E -2 0 E) 0 0)", true),
    ("insert_2", "InsertDelete", "((T E 0 2 (T E 1 0 E)) 0 0 0)", false),
    ("insert_2", "DeleteInsert", "((T E 0 0 E) 0 1 0)", true),
    ("insert_2", "InsertInsert", "(E 0 1 0 0)", false),
    ("insert_2", "InsertUnion", "(E (T E 0 0 E) 1 0)", true),
    ("insert_2", "UnionDeleteInsert", "((T E -2 0 E) E 0 0)", true),
    // insert_3
    ("insert_3", "InsertPost", "((T E 3 0 E) 3 3 1)", true),
    ("insert_3", "InsertModel", "((T E 0 1 E) 0 0)", true),
    ("insert_3", "InsertDelete", "((T (T E 0 0 E) 2 0 E) 2 2 0)", false),
    ("insert_3", "InsertInsert", "(E 0 0 1 0)", true),
    ("insert_3", "InsertUnion", "(E (T E 0 0 E) 1 0)", true),
    ("insert_3", "UnionDeleteInsert", "((T E -2 2 E) E -2 0)", true),
    // delete_4
    ("delete_4", "DeleteModel", "((T E 0 0 E) 1)", true),
    ("delete_4", "DeletePost", "((T E 0 0 E) 1 0)", true),
    ("delete_4", "DeleteDelete", "((T (T (T E 0 0 E) 3 5 E) 5 0 E) 5 3)", true),
    ("delete_4", "DeleteInsert", "(E 0 1 0)", true),
    ("delete_4", "DeleteUnion", "((T E -1 0 E) (T E 0 1 E) -1)", true),
    ("delete_4", "InsertDelete", "(E 0 1 0)", true),
    ("delete_4", "UnionDeleteInsert", "((T E 0 1 E) (T E 1 0 E) 0 0)", false),
    // delete_5
    ("delete_5", "DeleteModel", "((T (T E 1 0 E) 3 0 E) 1)", true),
    ("delete_5", "DeletePost", "((T (T E 2 0 E) 4 1 E) 2 2)", true),
    ("delete_5", "DeleteDelete", "((T E -4 0 (T E 4 4 E)) 4 -4)", true),
    ("delete_5", "DeleteInsert", "((T E 2 0 E) -2 -2 0)", true),
    ("delete_5", "DeleteUnion", "((T E -1 0 (T E 0 0 E)) (T E -2 2 E) -1)", true),
    ("delete_5", "UnionDeleteInsert", "((T (T E -1 0 E) 0 0 E) E 0 0)", false),
    // union_6
    ("union_6", "UnionValid", "((T E 0 0 E) (T E 0 0 E))", true),
    ("union_6", "UnionPost", "((T E 0 0 (T E 1 1 E)) (T E 0 0 E) 1)", true),
    ("union_6", "UnionModel", "((T E 0 0 E) (T E 0 0 E))", true),
    ("union_6", "DeleteUnion", "((T E 2 2 E) (T E -1 0 E) -1)", true),
    ("union_6", "InsertUnion", "(E (T E 0 0 E) 1 0)", true),
    ("union_6", "UnionDeleteInsert", "((T E 0 0 E) (T E 0 0 E) 0 0)", true),
    ("union_6", "UnionUnionAssoc", "((T E 0 1 E) (T E 0 1 E) (T E 0 0 E))", true),
    // union_7
    ("union_7", "UnionValid", "(E (T E 0 2 (T E 0 0 E)))", false),
    ("union_7", "UnionPost", "((T (T E -2 0 E) 2 0 E) (T E 0 0 E) -2)", true),
    ("union_7", "UnionModel", "((T E -1 0 E) (T (T E -2 1 E) 0 0 E))", true),
    ("union_7", "DeleteUnion", "((T E 0 0 E) (T (T E 0 0 E) 2 0 E) 2)", true),
    ("union_7", "InsertUnion", "((T E 0 0 E) (T E 1 1 E) 1 0)", true),
    ("union_7", "UnionDeleteInsert", "((T (T E -1 0 E) 0 0 E) E 0 0)", false),
    ("union_7", "UnionUnionAssoc", "((T E 0 0 E) (T E 1 0 E) (T E 1 1 E))", true),
    // union_8
    ("union_8", "UnionPost", "((T (T E 4 4 E) 2147483647 0 E) (T E 4 0 E) 4)", false),
    ("union_8", "UnionModel", "((T (T E -2 0 E) 2 0 E) (T E -2 1 E))", false),
    ("union_8", "DeleteUnion", "((T (T E -2 0 E) 1 0 E) (T E 0 0 E) 1)", false),
    ("union_8", "InsertUnion", "((T E 2 2 E) (T E -1 1 E) -1 0)", false),
    ("union_8", "UnionDeleteInsert", "((T E -1 3 E) (T E 3 1 E) -1 0)", false),
    ("union_8", "UnionUnionAssoc", "((T E 2 1 E) (T E 2 0 E) (T E 0 0 E))", false),
]

@Suite("Oracle")
struct OracleTests {

    /// Differential faithful-port proof: our verdict matches the reference
    /// (etna-python-bst) clean impl on every ground-truth input.
    @Test("Swift verdicts match the reference implementation on ETNA witnesses")
    func witnessesMatchReferenceImplementation() throws {
        for row in witnesses {
            let args = try witnessArgs(row.input)
            let result = try evaluate(property: row.property, args: args)
            #expect(
                result == row.expected,
                "\(row.mutation)/\(row.property) on \(row.input): expected \(row.expected) (reference), got \(String(describing: result))"
            )
        }
    }

    @Test("S-expr parse + decode round-trips")
    func sExprRoundTrip() throws {
        let tree = try decodeTree(parseSExpr("(T (T E 0 0 E) 2 5 E)"))
        #expect(tree == .T(.T(.E, 0, 0, .E), 2, 5, .E))
        #expect(tree.description == "(T (T (E) 0 0 (E)) 2 5 (E))")
    }

    @Test("isBST basics")
    func isBSTBasics() {
        #expect(isBST(.E))
        #expect(isBST(.T(.T(.E, 0, 0, .E), 1, 0, .T(.E, 2, 0, .E))))
        #expect(!isBST(.T(.E, 1, 0, .T(.E, 0, 0, .E)))) // right key < root
    }
}
