import Testing
@testable import BST

/// Milestone 1 — faithful-port proof. The `expected` verdict on each witness
/// (see `Fixtures.swift`) was generated by running the reference Python spec
/// (etna-python-bst) on each input, so this is a differential equivalence check:
/// our Swift verdict must match the reference verdict on every ground-truth
/// input. (16 of 52 are `false`: many properties precondition `isBST` on only
/// some arguments, so a witness with an invalid-BST argument fails on the
/// correct impl too.)
@Suite("Oracle")
struct OracleTests {

    @Test("Swift verdicts match the reference implementation on ETNA witnesses")
    func witnessesMatchReferenceImplementation() throws {
        for row in etnaWitnesses {
            let args = try witnessArgs(row.input)
            let result = try evaluate(property: row.property, args: args)
            #expect(
                result == row.expected,
                "\(row.mutation)/\(row.property) on \(row.input): expected \(row.expected) (reference), got \(String(describing: result))"
            )
        }
    }

    @Test("S-expr parse + decode round-trips")
    func sExprRoundTrip() throws {
        let tree = try decodeTree(parseSExpr("(T (T E 0 0 E) 2 5 E)"))
        #expect(tree == .T(.T(.E, 0, 0, .E), 2, 5, .E))
        #expect(tree.description == "(T (T E 0 0 E) 2 5 E)")
    }

    @Test("isBST basics")
    func isBSTBasics() {
        #expect(isBST(.E))
        #expect(isBST(.T(.T(.E, 0, 0, .E), 1, 0, .T(.E, 2, 0, .E))))
        #expect(!isBST(.T(.E, 1, 0, .T(.E, 0, 0, .E)))) // right key < root
    }
}
